### ISSUE TITLE
How can I help and take part in your project?

### ISSUE THREAD

**Issue by DmitryAleksandrovich** [Nelarius/wrenpp#1]
Hello! I'd like to join your project.
A little about yourself: I'm junior C++ developer, and I don't have commercial development experience. If you have tasks (junior), I'm happy to help project. Sorry with my not very confident English:)

**Comment by Nelarius** [comment]
Hi! And sorry for the longest ever issue response! 😅 

I don't really have any guidelines for contributing or for "joining" the project, but if you have any contributions to make, I'd be happy to look them over. Wren++ could use some work in Wren list and map access, for instance.
