### ISSUE TITLE
Support C++ global functions

### ISSUE THREAD

**Issue by SuperWangKai** [Nelarius/wrenpp#10]
How can we support global functions belong to no class?

**Comment by Nelarius** [comment]
Global functions can be added by calling `bindFunction<>()`:

```
#include "Wren++.h"
#include <cstdio>

static void greet() {
  std::printf("Hello, world\n");
}

int main() {
  wrenpp::beginModule( "main" )
    .beginClass( "Greeter" )
      .bindFunction< decltype(&greet), &greet >( true, "greet()" )
    .endClass()
  .endModule();

  wrenpp::VM vm;
  vm.executeString( "class Greeter {\n foreign static greet()\n }\n" );
  vm.executeString( "Greeter.greet()" );

  return 0;
}
```

**Comment by SuperWangKai** [comment]
Thank you very much for so quick response!

I just wonder how to bind global functions like the ones from math library. e.g. Abs/Min/Max/Sin...
We normally use them without any object prefix. for the convenience ie. Abs, Min ...

For the case of Wren, shall we use them as object's members? (It's not very appropriate to ask dumb language questions here though...)

**Comment by Nelarius** [comment]
No problem! 🙂 

Wren is very class-oriented, so you should be putting stand-alone functions as static methods in classes, like in Java or C#. Even if you declare a function variable, you can't import it into another module.

In the README on the front page of this repo, I have a little example of binding standard library math functions to foreign static methods: https://github.com/Nelarius/wrenpp#foreign-methods.

**Comment by SuperWangKai** [comment]
Thank you very much!
