### ISSUE TITLE
Define the C++ standard

### ISSUE THREAD

**Issue by IngwiePhoenix** [Nelarius/wrenpp#18]
For many, it is easier to compare compilers to the standards they support, and see if a project is compatible.

So, I would like to know, which C++ standard this library adheres to? From what I can see - but I haven't really seen everything... - I would actually believe it is C++99. But again, I am not sure - therefore I ask. :)

**Comment by Nelarius** [comment]
Wren++ requires c++14 due to the usage of the `decltype` specifier. Quite a few c++11 template features are used as well, unfortunately. I added a mention of the required compiler standard a little higher up in the readme 🙂

**Comment by IngwiePhoenix** [comment]
Ahh - alright. Thank you for that. :)
Well C++14 is a little too high… Are you aware of a C++99 library that will work with Wren?

**Comment by IngwiePhoenix** [comment]
Guess I gotta get cooking then - might try to implement a minimalistic aproach, then. :)

**Comment by Nelarius** [comment]
Good luck in your endeavors! 🙂
