### ISSUE TITLE
Wrong information about writing setters

### ISSUE THREAD

**Issue by Dugy** [Nelarius/wrenpp#5]
The information about the bindGetter function is wrong in the introduction in README.md. It shows an example that I should use bindGetter< decltype(&Vec3::x), &Vec3::x >( "x" ), while that one doesn't work, it should be bindGetter< decltype(Vec3::x), &Vec3::x >( "x" ), without the ampersand inside the decltype.

**Comment by Nelarius** [comment]
Thanks for spotting that and submitting the issue! I've changed the relevant parts in [6920d9](https://github.com/Nelarius/wrenpp/commit/6920d97c6079d63fe1417c6d43af34be4cdc8cd5). That example wasn't the only bit that was wrong :grimacing:
